services:
  mariadb:
    image: mariadb:10.11
    environment:
      - MARIADB_USER=usuariomoodle
      - MARIADB_PASSWORD=clavesegura
      - MARIADB_DATABASE=moodle_db
      - MARIADB_ROOT_PASSWORD=claveroot
    volumes:
      - mariadb_data:/var/lib/mysql

  moodle:
    build: .
    ports:
      - "8080:80"
    volumes:
      - moodledata:/var/www/moodledata
      - ./src_plugin/local_mejoras_examen:/var/www/html/local/mejoras_examen
      - ./src_plugin/local_qa_seed:/var/www/html/local/qa_seed
      - ./config.php:/var/www/html/config.php
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  moodledata: